Update msvs.py
Fixes an issue when vswhere may return characters outside the [00-127] range (an example may be the description param having some polish special characters). json.loads fails without this change in this way: 

  File "E:\conan-packages\cppcoro\tools\cake\src\cake\msvs.py", line 201, in vswhere
    return json.loads(out)
  File "E:\Python\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "E:\Python\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "E:\Python\Python27\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa2 in position 58: invalid start byte